### PR TITLE
replace NSObject hacks with define_method

### PR DESCRIPTION
**Pull request by siuying**
Replace the NSObject hacks with RubyMotion 1.24 define_method.

Also, I noticed the NSObject patch will cause bacon behave strangely (nested describe will not work).

### CODE REVIEW

**Comment by siuying** [comment]
On second thought, the "remove from cache" is probably not needed, as viewDidUnload is deprecated and not called in iOS6. What do you think?

**Comment by clayallsopp** [comment]
Hmm I'm going to merge it for now since it is the right way of doing that now/fixes Bacon.

But there does need to be a point at which we clear `shared_vc_cache`'s values, right? Or else the controllers will sit around in memory.

**Comment by siuying** [comment]
Maybe a global cleanup method to be called when needed (such as memory warning)?

**Comment by siuying** [comment]
the code "define_method(:new_dealloc)" is causing following crash on my old iPod touch

```
undefined local variable or method `shared_vc_cache' for # (NameError) callstack: 0x694463 0x69bbbd 0x61e805 0x69cfb1 0x68bd71 0x68d467 0x68c793 0x34c8a8 0x351790 0x68ea19 0x6962e5 0x68bd71 0x34c8a8 0x3518dc 0x35198c 0x31bcda37 0x31d153ad 0x353594ff 0x36215547 0x361a1097 0x352cd3eb 0x352cec1b 0x31ce00ed 0x31ce01e7 0x30931259 0x3092eb25 0x3092ee6b 0x3621c2ad 0x3619f4a5 0x3619f36d 0x31aa4439 0x31b5ccd5 0x1dd3db 0x1dcafc
```

I'd send a patch to remove the code. consider they are shared view controller, its okay to leave them to memory IMHO. in case it is really needed I can create a cleanup method for global memory warning case.

**Comment by siuying** [comment]
Is it because I called private shared_vc_cache in other controller classes? (but it do not complain about accessing private method ...)

**Comment by clayallsopp** [comment]
Hmm wait why is it under `class_eval` in the first place? I didn't notice that earlier. It takes the shared_vc_cache out of scope...

**Comment by siuying** [comment]
The class_eval block add new_dealloc to controller instance. my bad that i didnt test it.

what if do in this way? https://gist.github.com/3903654#file_specrouter_spec.rb

... but i still dont sure if this is right, apart from viewDidUnload deprecation, if it is a shared view controller, why remove it from cache when it is unloaded?

**Pull request merged**
